import os.path
import pytest

import reference.suffix_array

@pytest.mark.test_suffix_array
def test_array_generation():
    """
    See that appropriate suffix arrays are generated by the code in question

    unsorted suffixes: [ ["a","$", 0 ], ["$","a",1] ]
    """

    ag = reference.suffix_array.ArrayGenerator()

    with pytest.raises(Exception):
        suffixes = ag.generate_suffixes()

    suffixes = ag.generate_suffixes("a")
    assert suffixes == [["a","$",0],["$","a",1]]

    suffix_array = ag.generate_suffix_array(suffixes)

    assert suffix_array == [1,0]
    assert ag.burrows_wheeler_transform(suffix_array) == ["a","$"]